pipeline {
    agent any
    tools {
        maven 'Maven 3.3.3'
    }
    stages {
        stage('Compile') {
            steps {
                sh 'mvn clean compile'
            }
        } 
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Package') {
            steps {
                sh 'mvn -B -DskipTests package'
            }
        }        
    }
}
